apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbindeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      name: httpbinpod
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbinappcontainer
        image: ganeshsgani/http-bin:6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  type: NodePort
  selector:
    app: httpbin
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 80
    nodePort: 31130
