apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbindeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      name: httpbinpod
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbinappcontainer
        image: ganeshsgani/http-bin:6
        ports:
        - containerPort: 80
      resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  type: NodePort
  selector:
    app: httpbin
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 80
    nodePort: 31130
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpbindeployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
